services:
  - type: web
    name: n8n-on-render
    env: docker
    plan: free
    region: frankfurt         # ou oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: GENERIC_TIMEZONE
        value: "America/Toronto"
      - key: N8N_ENCRYPTION_KEY
        sync: false           # ajoute la valeur dans le dashboard Render après création
      - key: WEBHOOK_URL
        value: "https://example.onrender.com/"  # remplace après le 1er déploiement
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
