services:
  - type: web
    name: n8n
    env: docker
    region: oregon        # Amérique du Nord (Render ne propose pas "Canada", Oregon est le plus proche)
    plan: free            # optionnel (par défaut "starter")
    branch: main          # optionnel (par défaut "master")
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: PORT
        value: "5697"             # port personnalisé
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: America/Toronto    # fuseau horaire Canada
      - key: TZ
        value: America/Toronto
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

databases:
  - name: n8nDB
    region: oregon   # Amérique du Nord
    plan: free
