services:
  - type: web
    name: n8n-on-render
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT             # doit être 10000 côté Docker sur Render
        value: "10000"

      # Mets l'URL publique exacte APRÈS le 1er déploiement
      - key: WEBHOOK_URL
        value: "https://example.onrender.com/"
      - key: N8N_PUBLIC_URL
        value: "https://example.onrender.com/"
      - key: N8N_EDITOR_BASE_URL
        value: "https://example.onrender.com/"

      - key: GENERIC_TIMEZONE
        value: "America/Toronto"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"

      # Ajoute la valeur (secret) dans Render, ne la commit pas
      - key: N8N_ENCRYPTION_KEY
        sync: false

    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
